version: '3.4'

services:

    sqlserver:
        container_name: sqlserver
        image: mcr.microsoft.com/azure-sql-edge
        environment:
            - ACCEPT_EULA=1
            - MSSQL_SA_PASSWORD=MyPass@word
            - MSSQL_PID=Developer
            - MSSQL_USER=SA
        ports:
            - '1433:1433'

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management
        hostname: 'rabbitmq'
        ports:
            - '4369:4369'
            - '5671:5671'
            - '5672:5672'
            - '25672:25672'
            - '15671:15671'
            - '15672:15672'

    seq:
        container_name: seq
        image: datalust/seq
        environment:
            - ACCEPT_EULA=y
        ports:
            - '5341:80'

    # banksim-api:
    #  image: banksim-api
    #  build:
    #    context: .
    #    dockerfile: banksim.Dockerfile
    #  ports:
    #    - '7209:443'

    # gateway-api:
    #  image: gateway-api
    #  build:
    #    context: .
    #    dockerfile: gateway.Dockerfile
    #  ports:
    #     - '7099:443'

    # ingestion-svc:
    #  image: ingestion-svc
    #  build:
    #    context: .
    #    dockerfile: ingestion.Dockerfile
    #  ports:
    #     - '7964:443'

    # acquiring-svc:
    #  image: acquiring-svc
    #  build:
    #    context: .
    #    dockerfile: acquiring.Dockerfile
    #  ports:
    #     - '7345:443'

    # processing-svc:
    #  image: processing-svc
    #  build:
    #    context: .
    #    dockerfile: processing.Dockerfile
    #  ports:
    #     - '7814:443'